React demo
SuduguTejasvi/SuduguTejasvi-tejasvisudugu_ldp pull request #20
Opened 2024-07-09 01:03 UTC by SuduguTejasvi

React myntra card Demo application

2024-07-09 01:08 UTC, SuduguTejasvi commented
<img width="497" alt="image" src="https://github.com/SuduguTejasvi/SuduguTejasvi-tejasvisudugu_ldp/assets/170507197/125d3b3b-b22e-47c0-a606-55ac6aca2bac">

2024-07-09 06:03 UTC, SaiSree-0517 reviewed
can you just brief where have you added font family

2024-07-09 06:12 UTC, SaiSree-0517 commented on src/Themes/index.tsx
where have you used this theme file

2024-07-09 06:20 UTC, SuduguTejasvi commented on src/Themes/index.tsx
I downloaded a font from Google and pasted it into the fonts folder within the public directory. I declared the font using @font-face in styles.css located in the src directory, and then imported styles.css in index.tsx. I used that font in themes.

2024-07-09 06:25 UTC, SuduguTejasvi commented on src/Themes/index.tsx
I used a theme file in App.tsx. I imported the file and provided the themes in ThemeProvider

2024-07-09 10:08 UTC, SaiSree-0517 commented
check the styling User experience designer font weight is not matching the figma

2024-07-10 08:10 UTC, SaiSree-0517 requested changes

2024-07-10 08:10 UTC, SaiSree-0517 commented on src/components/organism/Card/index.tsx
> +            <Title v1="h3" v2="h4" v3="h6" path="/asserts/images/more.svg" text1="User Experience Designer" text2="Myntra" text3="Hitech city Hyderabad -500072" />
get these values from constants file

2024-07-12 06:49 UTC, SuduguTejasvi commented on src/components/organism/Card/index.tsx
> +            <Title v1="h3" v2="h4" v3="h6" path="/asserts/images/more.svg" text1="User Experience Designer" text2="Myntra" text3="Hitech city Hyderabad -500072" />
Mam, I added a constants file in src and imported images using these constants. Could you please review it and let me know if any changes are required? I also adjusted the font weight according to the Figma design.

<img width="488" alt="image" src="https://github.com/user-attachments/assets/b1565923-a6e3-4d7f-a267-5dd05ef7a43c">

2024-07-12 10:54 UTC, SaiSree-0517 approved these changes

2024-07-12 11:28 UTC, merged